# Generated by Django 4.1.7 on 2023-03-05 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0002_studenttasks_delete_calculations'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttasks',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mastersolvedtasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studenttasks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studenttask', to=settings.AUTH_USER_MODEL),
        ),
    ]
